### ISSUE TITLE
Menambahkan dan Mengganti Backgroud pada slider label

### ISSUE THREAD

**Issue by BerkasKita** [BerkasKita/AHStream#2]
# Preview
<img alt="" src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjHNS8vJ7EXn66CSQuIhDsf_AIMJ-O0KW2CMOmC2aT0AJaWf9A_7rJzeOjpF9hY0N7cglj4cEFrDSdOKeQAniYgpJ77_lJy9Dg5ira8veU12GSWkmw-WbCLVVA8cEOSA15Jj2jK3e_opOtWsSRI78PdD23JyEcZeraPNWcrY6MP2scWG4YTJ2IHhikA9r-k/s0/jjsdfsdjfsjdfklsdlfjslkdflsdjflksdlfksdf.jpg" loading="lazy">

# Langkah - langkah
## Menambahkan
+ Pergi ke `Thema`
+ Masuk dalam `Edit HTML`
+ Cari `.label_genres.Romance .bg_label {...}` dan letakan kode ini dibawahnya

    ```css
    .label_genres.Nama_Label .bg_label {
      background-image: url("URL_");
    }
    ```
    | Name | Description |
    | ------------- | ------------- |
    | Nama_Label  | Isi dengan nama label |
    | URL_ | Isi dengan url image |
+ Setelah melakukan perubahan jangan lupa `Simpan`

> [!NOTE]  
> Ukuran gambar yang disarankan `150x150`

## Mengganti
+ Pergi ke `Thema`
+ Masuk dalam `Edit HTML`
+ Cari Backgroud yang ingin diganti misal

    ```css
    .label_genres.Nama_Label .bg_label {
      background-image: url("URL_");
    }
    ```
    | Name | Description |
    | ------------- | ------------- |
    | Nama_Label  | Isi dengan nama label |
    | URL_ | Isi dengan url image |
+ Setelah melakukan perubahan jangan lupa `Simpan`

> [!NOTE]  
> Ukuran gambar yang disarankan `150x150`
